apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: anirudh2903/crudop_java_app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://java-db-service:5432/postgres"
        - name: DATABASE_USERNAME
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-db
  template:
    metadata:
      labels:
        app: java-db
    spec:
      containers:
      - name: postgres-container
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: pgdata
        emptyDir: {}
