# JAVA APP DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels: 
        app: java-app
    spec:
      containers:
        - name: java-app
          image: maven:3.8.4-openjdk-17
          command: ["mvn","clean","package","-DskipTests"]
          args:
            - -f
            - /
          volumeMounts:
            - name: maven-cache
              mountPath: /root/.m2/repository
        - name: java-app-runtime
          image: openjdk:17-jdk-alpine
          command: ["java", "-jar", "/crudop-0.0.1-SNASHOT.jar"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-jar
              mountPath: /crudop-0.0.1-SNAPSHOT.jar
      volumes:
        - name: maven-cache
          emptyDir: {}
        - name: app-jar
          emptyDir: {}


# JAVA DB DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-db-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-db
  template:
    metadata:
      labels: 
        app: java-db
    spec:
      containers:
        - name: java-db
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data

# for deploying persistent volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mavne-cache-pv
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/kubernetes/volumes/maven-cache"

# for deploying persistent volume claim

apiVolume: v1
kind: PersistentVolumeClaim
metadata: 
  name: maven-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


