apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: java-db-service
spec:
  selector:
    app: java-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
